In [1]:
import gym
from gym.spaces import Box
import numpy as np
from numpy.random import default_rng


class InventoryEnv(gym.Env):
    def __init__(self):
        """
        Must define self.observation_space and self.action_space here
        """
        self.max_capacity = 4000

        self.action_space = Box(low=np.array([0]), high=np.array([self.max_capacity]))

        self.lead_time = 5
        self.obs_dim = self.lead_time + 4

        self.max_mean_daily_demand = 200
        self.max_unit_selling_price = 100
        self.max_daily_holding_cost_per_unit = 5

        obs_low = np.zeros((self.obs_dim,))
        obs_high = np.array([self.max_capacity for _ in range(self.lead_time)] +
                            [self.max_mean_daily_demand, self.max_unit_selling_price,
                             self.max_unit_selling_price, self.max_daily_holding_cost_per_unit
                             ]
                            )
        self.observation_space = Box(low=obs_low, high=obs_high)

        self.rng = default_rng()

        self.current_obs = None
        self.episode_length_in_days = 90
        self.day_num = None

    def reset(self):
        """
        Returns: the observation of the initial state
        Reset the environment to initial state so that a new episode (independent of previous ones) may start
        """
        mean_daily_demand = self.rng.uniform() * self.max_mean_daily_demand
        selling_price = self.rng.uniform() * self.max_unit_selling_price
        buying_price = self.rng.uniform() * selling_price
        daily_holding_cost_per_unit = self.rng.uniform() * min(buying_price,
                                                               self.max_daily_holding_cost_per_unit
                                                               )
        self.current_obs = np.array([0 for _ in range(self.lead_time)] +
                                    [mean_daily_demand, selling_price, buying_price,
                                     daily_holding_cost_per_unit,
                                     ]
                                    )
        self.day_num = 0
        return self.current_obs

    def step(self, action):
        """
        Returns: Given current obs and action, returns the next observation, the reward, done and optionally additional info
        """
        buys = min(action[0], self.max_capacity - np.sum(self.current_obs[:self.lead_time]))

        demand = self.rng.poisson(self.current_obs[self.lead_time])
        next_obs = np.concatenate((self.current_obs[1: self.lead_time],
                                   np.array([buys]),
                                   self.current_obs[self.lead_time:]
                                   )
                                  )
        next_obs[0] += max(0, self.current_obs[0] - demand)

        reward = (self.current_obs[self.lead_time + 1] * (self.current_obs[0] + self.current_obs[1] - next_obs[0]) -
                  self.current_obs[self.lead_time + 2] * buys -
                  self.current_obs[self.lead_time + 3] * (next_obs[0] - self.current_obs[1])
                  )

        self.day_num += 1
        done = False
        if self.day_num >= self.episode_length_in_days:
            done = True

        self.current_obs = next_obs

        return self.current_obs, reward, done, {}

    def render(self, mode="human"):
        """
        Returns: None
        Show the current environment state e.g. the graphical window in `CartPole-v1`
        This method must be implemented, but it is OK to have an empty implementation if rendering is not
        important
        """
        pass

    def close(self):
        """
        Returns: None
        This method is optional. Used to cleanup all resources (threads, graphical windows) etc.
        """
        pass

    def seed(self, seed=None):
        """
        Returns: List of seeds
        This method is optional. Used to set seeds for the environment's random number generator for
        obtaining deterministic behavior
        """
        return

In [33]:
from gym import ObservationWrapper


# ----- SOLUTION ----- #
# Deriving from the convenience class ObservationWrapper, since the required observation modification is not action/transition dependent
class ModifyObservation(ObservationWrapper):
    # ----- SOLUTION ----- #
    # Adjust observation space to match InventoryEnvHard
    def __init__(self, env):
        super().__init__(env)
        self.max_goodwill_penalty_per_unit = 10
        obs_low = self.env.observation_space.low
        obs_high = self.env.observation_space.high
        self.observation_space = Box(
            low = np.append(obs_low, 0),
            high = np.append(obs_high, self.max_goodwill_penalty_per_unit)
        )
        
    # ----- SOLUTION ----- #
    # For each episode, we need a new random value for goodwill_penalty_per_unit
    # This value should be stored as an instance variable, so that other methods can use it while an episode is running
    def reset(self):
        self.goodwill_penalty_per_unit = self.env.rng.uniform() * self.max_goodwill_penalty_per_unit
        return super().reset()
    
    # ----- SOLUTION ----- #
    # The state in InventoryEnvHard has one additional element compared to InventoryEnv
    # It's the goodwill_penalty_per_unit
    def observation(self, obs):
        return np.append(obs, self.goodwill_penalty_per_unit)

In [34]:
env = InventoryEnv()
wrapped = ModifyObservation(env)

Notice how the state has one more element compared to the original env

In [35]:
wrapped.reset()    # wrapped env

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       42.42022703, 62.06303903, 39.9094024 ,  2.1053574 ,  0.37887513])

In [36]:
env.reset()    # original env

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        , 105.86627505,  78.01492857,  70.82760083,
         4.1408501 ])

We get different values of `goodwill_penalty_per_unit` for each episode, as expected

In [37]:
wrapped.reset()    # last element has a new random value

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       22.79089771, 46.65425202, 25.46906165,  3.59833574,  2.43142205])

The next state preserves the value of `goodwill_penalty_per_unit`, as expected

In [38]:
obs, _, _, _ = wrapped.step(wrapped.action_space.sample())
print(obs)

[  0.           0.           0.           0.         174.41824341
  22.79089771  46.65425202  25.46906165   3.59833574   2.43142205]


Notice how the observation space of the wrapped environment has one additional dimension compared to the original environment. If you don't define this correctly in the wrapped environment, `rllib` will complain since it checks whether the observations belong to the observation space.

In [39]:
wrapped.observation_space

Box([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], [4000. 4000. 4000. 4000. 4000.  200.  100.  100.    5.   10.], (10,), float32)

In [40]:
env.observation_space

Box([0. 0. 0. 0. 0. 0. 0. 0. 0.], [4000. 4000. 4000. 4000. 4000.  200.  100.  100.    5.], (9,), float32)